version: "2.1"
services:
  laminas:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - .:/var/www
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=${PMA_HOST}
  db:
    image: mariadb:10.2
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'unity'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: 'Europe/Berlin'
    volumes:
      - ./data/sql/:/var/sql:ro
      - /home/lidia/srv/mysql/:/var/lib/mysql
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  172.18.0.0/16
