<?php
$title = 'My users';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('user', ['action' => 'add']) ?>">Add new user</a>
</p>

<table class="table">
    <tr>
        <th>Username</th>
        <th>Password</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Is Admin</th>
        <th>Id Clinic</th>
        <th>&nbsp;</th>
    </tr>
    <?php
    $users = new ArrayObject();
    foreach ($users as $user) : ?>
        <tr>
            <td><?= $this->escapeHtml($user->username) ?></td>
            <td><?= $this->escapeHtml($user->password) ?></td>
            <td><?= $this->escapeHtml($user->firstName) ?></td>
            <td><?= $this->escapeHtml($user->lastName) ?></td>
            <td><?= $this->escapeHtml($user->isAdmin) ?></td>
            <td><?= $this->escapeHtml($user->idClinic) ?></td>
            <td>
                <a href="<?= $this->url('user', ['action' => 'edit', 'id' => $user->id]) ?>">Edit</a>
                <a href="<?= $this->url('user', ['action' => 'delete', 'id' => $user->id]) ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>